"""
PHASE 1 -- correctif hemisphere, applique a la SOURCE DE VERITE.

notebooks/simulation_functions.py porte l'en-tete
"Auto-generated by 02_simulation.ipynb -- DO NOT EDIT MANUALLY", et la CI
(job notebook-export-drift-check) regenere le fichier depuis le notebook
puis le diffe. Editer le .py seul ferait donc echouer la CI.

Ce script :
  1. modifie compute_POA dans la cellule 2 du notebook ;
  2. regenere simulation_functions.py EXACTEMENT comme la CI le fait
     (memes cellules de definition, meme cellule d'export) ;
  3. verifie que le diff ne touche que compute_POA.
"""
import difflib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent / "repo"
NB = REPO / "notebooks" / "02_simulation.ipynb"
PY = REPO / "notebooks" / "simulation_functions.py"

DEF_CELL_INDICES = [2, 3, 4, 5, 6]      # identiques a .github/workflows/tests.yml
EXPORT_CELL_INDEX = 8

# ----------------------------------------------------------------------
# 1. Remplacements dans compute_POA
# ----------------------------------------------------------------------
OLD_DOC_HEAD = '''    Compute plane-of-array (POA) irradiance for a south-facing fixed-tilt
    surface using the isotropic sky model (Eq. 7–8).

    G_front = DNI*cos(theta_i) + DHI*(1+cos(beta))/2 + GHI*rho_g*(1-cos(beta))/2
    G_rear  = GHI * rho_g * (1 - F_shad) * phi_rear_fraction
    G_eff   = G_front + phi * G_rear

    Angle of incidence (Eq. 8, CORRECTED):
        cos(theta_i) = sin(delta)*sin(phi - beta) + cos(delta)*cos(H)*cos(phi - beta)

    This is the exact closed-form angle-of-incidence for a fixed, due-south
    facing surface (Duffie & Beckman, "Solar Engineering of Thermal Processes"),
    a function of declination (delta), hour angle (H), latitude (phi), and tilt
    (beta). It correctly varies through the day as the sun moves east to west.
'''

NEW_DOC_HEAD = '''    Compute plane-of-array (POA) irradiance for an EQUATOR-FACING fixed-tilt
    surface using the isotropic sky model (Eq. 7–8).

    G_front = DNI*cos(theta_i) + DHI*(1+cos(beta))/2 + GHI*rho_g*(1-cos(beta))/2
    G_rear  = GHI * rho_g * (1 - F_shad) * phi_rear_fraction
    G_eff   = G_front + phi * G_rear

    Angle of incidence (Eq. 8):
        cos(theta_i) = sin(delta)*sin(phi_eff) + cos(delta)*cos(H)*cos(phi_eff)
        phi_eff      = phi - beta   in the NORTHERN hemisphere (faces due south)
                     = phi + beta   in the SOUTHERN hemisphere (faces due north)

    This is the exact closed-form angle-of-incidence of Duffie & Beckman
    ("Solar Engineering of Thermal Processes") for a fixed collector turned
    towards the equator, a function of declination (delta), hour angle (H),
    latitude (phi), and tilt (beta). It correctly varies through the day as
    the sun moves east to west.

    HEMISPHERE CORRECTION (fixed 2026-09)
    -------------------------------------
    The previous version used (phi - beta) unconditionally — the Duffie &
    Beckman form for surface azimuth gamma = 0, i.e. a due-south collector.
    That is exact in the northern hemisphere and wrong everywhere south of
    the equator, where the collector must face north (gamma = 180°). All four
    published study sites are northern, so the error stayed invisible until
    the model was applied across Africa.

    Measured impact (audit/phase0, same climate, latitude varied so the
    geometry is isolated): annual POA error from -8.1 % near the equator to
    -32.0 % at 35°S, and up to -30.1 % on annual PV yield. Northern-hemisphere
    results are unchanged to 0.000 %.

    Sign convention — np.sign() is deliberately NOT used here. np.sign(0.0)
    returns 0, which would cancel beta entirely at exactly lat = 0 and
    silently treat the array as horizontal. The convention adopted is
    lat >= 0 -> northern (faces south); at exactly the equator the two
    orientations are equivalent over a full year by symmetry, so the choice
    is arbitrary — but it must be explicit and tested rather than emergent.
    See tests/test_hemisphere.py.

    LIMITATION — the surface azimuth is not a free parameter. Only
    equator-facing rows are representable. East-west oriented rows, a real
    agrivoltaic configuration, would need the full Duffie & Beckman
    expression with an explicit surface_azimuth argument; that refactor is
    deliberately out of scope here (see docs/presizing_platform_roadmap.md).
'''

OLD_PARAM_DOC = '''    lat_deg  : site latitude (degrees) — required for the angle-of-incidence
               formula; NOT optional, since south-facing AoI depends on
               (phi - beta), not on beta alone.
'''

NEW_PARAM_DOC = '''    lat_deg  : site latitude (degrees, NEGATIVE in the southern hemisphere)
               — required both for the angle-of-incidence formula, which
               depends on (phi ∓ beta) rather than on beta alone, and to
               decide which way the collector faces.
'''

OLD_CODE = '''    # Angle of incidence on tilted, due-south surface (Duffie & Beckman)
    cos_theta_i = np.clip(
        np.sin(dec_r) * np.sin(lat_r - beta_r)
        + np.cos(dec_r) * np.cos(ha_r) * np.cos(lat_r - beta_r),
        0, 1
    )
'''

NEW_CODE = '''    # Angle of incidence on a tilted, equator-facing surface (Duffie & Beckman).
    # hemisphere = +1 north (collector faces due south), -1 south (faces due north).
    # np.sign() is NOT used: np.sign(0.0) == 0 would drop beta at the equator.
    hemisphere = 1.0 if lat_deg >= 0 else -1.0
    phi_eff_r  = lat_r - hemisphere * beta_r

    cos_theta_i = np.clip(
        np.sin(dec_r) * np.sin(phi_eff_r)
        + np.cos(dec_r) * np.cos(ha_r) * np.cos(phi_eff_r),
        0, 1
    )
'''

REPLACEMENTS = [
    (OLD_DOC_HEAD, NEW_DOC_HEAD),
    (OLD_PARAM_DOC, NEW_PARAM_DOC),
    (OLD_CODE, NEW_CODE),
]


def patch_notebook():
    nb = json.loads(NB.read_text(encoding="utf-8"))
    src = "".join(nb["cells"][2]["source"])

    for old, new in REPLACEMENTS:
        if old not in src:
            raise SystemExit(
                "ECHEC : bloc introuvable dans la cellule 2 du notebook.\n"
                "Le notebook a change depuis l'audit ; revoir le patch.\n"
                f"--- bloc attendu ---\n{old[:200]}"
            )
        if src.count(old) != 1:
            raise SystemExit(f"ECHEC : bloc present {src.count(old)} fois, attendu 1 fois.")
        src = src.replace(old, new)

    # nbformat stocke la source en liste de lignes, fin de ligne comprise
    nb["cells"][2]["source"] = src.splitlines(keepends=True)
    NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"notebook patche : {NB.name}")


def regenerate_like_ci():
    """Reproduit exactement le job notebook-export-drift-check."""
    nb = json.loads(NB.read_text(encoding="utf-8"))

    ns = {}
    exec("import numpy as np", ns)
    exec("import pandas as pd", ns)
    sys.path.insert(0, str(REPO / "notebooks"))
    exec("from config_00 import SITES, PARAMS, DE_SETTINGS, SCENARIOS", ns)

    for idx in DEF_CELL_INDICES:
        exec("".join(nb["cells"][idx]["source"]), ns)

    export_src = "".join(nb["cells"][EXPORT_CELL_INDEX]["source"])
    export_src = export_src.replace(
        'out_path = Path.cwd() / "simulation_functions.py"',
        f'out_path = Path(r"{PY}")',
    )
    exec(export_src, ns)
    print(f"regenere depuis le notebook : {PY.name}")


if __name__ == "__main__":
    before = PY.read_text(encoding="utf-8")
    patch_notebook()
    regenerate_like_ci()
    after = PY.read_text(encoding="utf-8")

    diff = list(difflib.unified_diff(
        before.splitlines(), after.splitlines(),
        fromfile="avant", tofile="apres", lineterm="", n=1))

    changed = [l for l in diff if l.startswith(("+", "-")) and not l.startswith(("+++", "---"))]
    print(f"\nlignes modifiees : {len(changed)}")

    # Garde-fou : le diff ne doit toucher que compute_POA
    hunks = [l for l in diff if l.startswith("@@")]
    print(f"blocs de diff    : {len(hunks)}")
    print("\n".join(diff[:12]))
    print("  [...]")
