# simulation_functions.py
# Auto-generated by 02_simulation.ipynb — DO NOT EDIT MANUALLY
# Re-run 02_simulation.ipynb to regenerate.

import numpy as np
import pandas as pd
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config_00 import SITES, PARAMS, DE_SETTINGS, SCENARIOS

MODULE_LENGTH_M = 2.278
MODULE_WIDTH_M  = 1.134
ROW_LENGTH_M    = 100.0
LAND_AREA_M2    = 10_000

def compute_solar_angles(df: pd.DataFrame, lat_deg: float) -> pd.DataFrame:
    """
    Compute hourly solar elevation angle (alpha_s) and hour angle.
    Uses the Spencer (1971) declination formula.

    Parameters
    ----------
    df      : hourly DataFrame with DatetimeIndex (UTC)
    lat_deg : site latitude in degrees

    Returns
    -------
    df with new columns: declination_deg, hour_angle_deg, solar_elevation_deg
    """
    idx  = pd.DatetimeIndex(df.index)
    doy  = idx.day_of_year.values.astype(float)
    hour = idx.hour.values.astype(float) + idx.minute.values / 60.0

    # Spencer (1971) declination (degrees)
    B   = 2 * np.pi * (doy - 1) / 365
    dec = (180 / np.pi) * (
        0.006918
        - 0.399912 * np.cos(B)
        + 0.070257 * np.sin(B)
        - 0.006758 * np.cos(2*B)
        + 0.000907 * np.sin(2*B)
        - 0.002697 * np.cos(3*B)
        + 0.00148  * np.sin(3*B)
    )

    # Hour angle (degrees): 0 at solar noon, negative morning
    hour_angle = (hour - 12) * 15  # 15°/hour

    # Solar elevation angle (degrees)
    lat_r = np.radians(lat_deg)
    dec_r = np.radians(dec)
    ha_r  = np.radians(hour_angle)

    sin_elev = (
        np.sin(lat_r) * np.sin(dec_r)
        + np.cos(lat_r) * np.cos(dec_r) * np.cos(ha_r)
    )
    solar_elev = np.degrees(np.arcsin(np.clip(sin_elev, -1, 1)))

    df = df.copy()
    df["declination_deg"]    = dec
    df["hour_angle_deg"]     = hour_angle
    df["solar_elevation_deg"] = solar_elev
    return df


def compute_shading(df: pd.DataFrame,
                    beta_deg: float,
                    d_row_m: float,
                    H_m_m: float) -> pd.DataFrame:
    """
    Compute hourly ground shading fraction F_shad (Equation 6).

    F_shad = min(1,  H_m * cos(Δγ) / (d_row * tan(α_s)))

    where:
      H_m    = module bottom-edge height (m)
      Δγ     = azimuth difference (0 for south-facing rows)
      d_row  = row spacing (m)
      α_s    = solar elevation angle (degrees)

    F_shad = 0 at night (α_s ≤ 0) and during summer midday (sun too high).
    GCR    = module_width_projected / d_row
           = (module_length * cos(beta)) / d_row
    Module length (Jinko 550Wp) = 2.278 m

    Parameters
    ----------
    df       : DataFrame with solar_elevation_deg column
    beta_deg : panel tilt angle (degrees)
    d_row_m  : row spacing (m)
    H_m_m    : module bottom-edge height (m)

    Returns
    -------
    df with new columns: F_shad, GCR
    """
    MODULE_LENGTH_M = 2.278    # Jinko Tiger Neo 550Wp
    delta_gamma     = 0.0      # azimuth difference — south-facing rows

    alpha_s = df["solar_elevation_deg"].values
    tan_alpha = np.tan(np.radians(np.clip(alpha_s, 0.1, 90)))

    # Shading fraction (Eq. 6)
    F_shad_raw = (H_m_m * np.cos(np.radians(delta_gamma))
                  / (d_row_m * tan_alpha))
    F_shad = np.where(alpha_s <= 0, 0.0,
                      np.clip(F_shad_raw, 0.0, 1.0))

    # Ground Coverage Ratio
    GCR = (MODULE_LENGTH_M * np.cos(np.radians(beta_deg))) / d_row_m

    df = df.copy()
    df["F_shad"] = F_shad
    df["GCR"]    = GCR
    return df


def compute_POA(df: pd.DataFrame, beta_deg: float) -> pd.DataFrame:
    """
    Compute plane-of-array (POA) irradiance for a south-facing fixed-tilt
    surface using the isotropic sky model (Eq. 7–8).

    G_front = DNI*cos(theta_i) + DHI*(1+cos(beta))/2 + GHI*rho_g*(1-cos(beta))/2
    G_rear  = GHI * rho_g * (1 - F_shad) * phi_rear_fraction
    G_eff   = G_front + phi * G_rear

    Parameters
    ----------
    df       : DataFrame with GHI, DNI, DHI, solar_elevation_deg, F_shad
    beta_deg : tilt angle (degrees)

    Returns
    -------
    df with columns: G_front, G_rear, G_eff
    """
    P     = PARAMS
    beta_r = np.radians(beta_deg)
    lat_r  = 0  # angle of incidence for south-facing at optimal tilt ≈ small

    # Angle of incidence on tilted surface (simplified for south-facing)
    alpha_r = np.radians(df["solar_elevation_deg"].values)
    cos_theta_i = np.clip(
        np.sin(alpha_r) * np.cos(beta_r)
        + np.cos(alpha_r) * np.sin(beta_r),
        0, 1
    )

    GHI = df["GHI"].values
    DNI = df["DNI"].values
    DHI = df["DHI"].values

    # Front surface (isotropic sky model)
    G_beam    = DNI * cos_theta_i
    G_diffuse = DHI * (1 + np.cos(beta_r)) / 2
    G_reflect = GHI * P["rho_ground"] * (1 - np.cos(beta_r)) / 2
    G_front   = np.clip(G_beam + G_diffuse + G_reflect, 0, None)

    # Rear surface — reduced by shading fraction
    phi_rear  = 0.12   # rear irradiance as fraction of front (APV ground reflected)
    G_rear    = GHI * P["rho_ground"] * (1 - df["F_shad"].values) * phi_rear
    G_rear    = np.clip(G_rear, 0, None)

    # Effective bifacial irradiance
    G_eff = G_front + P["bifaciality"] * G_rear

    df = df.copy()
    df["G_front"] = G_front
    df["G_rear"]  = G_rear
    df["G_eff"]   = G_eff
    return df


def compute_PV(df: pd.DataFrame,
               n_modules: int,
               f_PV_heat: float) -> pd.DataFrame:
    """
    Compute hourly PV power output using Faiman cell temperature model.

    Cell temperature (Eq. 9 — Faiman 2008):
        T_cell = T_amb + G_eff / (U0 + U1 * WS)

    PV power (Eq. 10):
        P_PV = P_STC * N * (1 - eta_loss)
               * [1 + beta_p * (T_cell - 25)]
               * G_eff / 1000

    Energy allocation:
        E_PV_heat = f_PV_heat * P_PV   (fraction used to heat digester)
        E_PV_sold = (1 - f_PV_heat) * P_PV

    Parameters
    ----------
    df        : DataFrame with G_eff, T2m, WS columns
    n_modules : number of PV modules on 1 ha
    f_PV_heat : fraction of PV energy allocated to digester heating

    Returns
    -------
    df with columns: T_cell, P_PV_W, E_PV_kWh, E_PV_heat_kWh, E_PV_sold_kWh
    """
    P = PARAMS

    G_eff = df["G_eff"].values
    T_amb = df["T2m"].values
    WS    = df["WS"].values

    # Faiman cell temperature (Eq. 9)
    T_cell = T_amb + G_eff / (P["U0"] + P["U1"] * np.clip(WS, 0.5, None))

    # PV power per module (W) — Eq. 10
    eta_temp = 1 + P["beta_p"] * (T_cell - 25)
    P_module = (P["P_STC_Wp"]
                * (1 - P["eta_loss"])
                * np.clip(eta_temp, 0, None)
                * G_eff / 1000)
    P_module = np.clip(P_module, 0, None)

    # Total array power (W) → energy (kWh/h = kWh per hour)
    P_array_W    = P_module * n_modules
    E_PV_kWh     = P_array_W / 1000          # kWh per hour

    # Allocate to heating vs. grid
    E_PV_heat_kWh = f_PV_heat * E_PV_kWh
    E_PV_sold_kWh = (1 - f_PV_heat) * E_PV_kWh

    df = df.copy()
    df["T_cell"]         = T_cell
    df["P_PV_W"]         = P_array_W
    df["E_PV_kWh"]       = E_PV_kWh
    df["E_PV_heat_kWh"]  = E_PV_heat_kWh
    df["E_PV_sold_kWh"]  = E_PV_sold_kWh
    return df


def compute_crop_yield(df: pd.DataFrame,
                       PAR_sat: float = 174.0) -> dict:
    """
    Compute crop yield ratio LER_crop using the PAR integral method (Eq. 11).

    PAR under APV panels:
        PAR_AV(t)   = GHI(t) * f_PAR * (1 - F_shad(t))

    Open-field PAR (reference):
        PAR_open(t) = GHI(t) * f_PAR

    Yield ratio (Eq. 11):
        LER_crop = ∫ min(PAR_AV, PAR_sat) dt  /  ∫ PAR_open dt

    Integration is over the growing season only (in_season == True).

    Parameters
    ----------
    df      : DataFrame with GHI, F_shad, in_season columns
    PAR_sat : light saturation point (W/m²) — 174 tomato, 76 lettuce

    Returns
    -------
    dict with LER_crop, integral_APV, integral_open
    """
    P = PARAMS
    season = df["in_season"].values.astype(bool)

    GHI_s    = df["GHI"].values[season]
    F_shad_s = df["F_shad"].values[season]

    PAR_open = GHI_s * P["f_PAR"]
    PAR_AV   = PAR_open * (1 - F_shad_s)

    # Numerator: APV PAR capped at saturation
    integral_APV  = np.sum(np.minimum(PAR_AV,   PAR_sat))
    # Denominator: open-field PAR (NOT capped — this is correct)
    integral_open = np.sum(PAR_open)

    if integral_open < 1e-6:
        return {"LER_crop": 0.0,
                "integral_APV": 0.0, "integral_open": 0.0}

    LER_crop = integral_APV / integral_open

    return {
        "LER_crop":       float(np.clip(LER_crop, 0, 2)),
        "integral_APV":   float(integral_APV),
        "integral_open":  float(integral_open),
    }


def compute_ET_reduction(df: pd.DataFrame,
                         site: str) -> dict:
    """
    Compute growing-season water savings from APV shading (Eq. 14).

    ET_APV(t) = ET0(t) * (1 - alpha_shade * F_shad(t))
    W_saved   = Σ [ET0(t) - ET_APV(t)]  over growing season
              = Σ alpha_shade * F_shad(t) * ET0(t)

    ET0 is loaded from the pre-computed column (added by 01_load_data if
    available) or estimated from GHI via the Hargreaves formula.

    IMPORTANT: denominator of LER_water uses ET0_SEASON (not annual).
    This is the corrected definition — see manuscript discussion.

    Returns
    -------
    dict with W_saved_mm, ET0_season_mm, ET0_annual_mm,
               LER_water_season_pct, LER_water_annual_pct
    """
    P = PARAMS
    cfg = SITES[site]
    season = df["in_season"].values.astype(bool)

    # Hourly ET0 estimate: daily ET0 distributed uniformly over daylight hours
    # Use pre-computed daily ET0 if available, otherwise estimate from GHI
    GHI   = df["GHI"].values
    T2m   = df["T2m"].values

    # Simple hourly ET0 proxy: proportional to GHI during daytime
    # Normalized so daily sum matches Hargreaves daily total
    # (full Penman-Monteith would need RH and WS — added in future upgrade)
    GHI_daily = pd.Series(GHI).groupby(
        pd.DatetimeIndex(df.index).date).transform("sum").values
    GHI_daily  = np.where(GHI_daily < 1, 1, GHI_daily)

    # Hargreaves daily ET0 (mm/day) — vectorized
    doy    = pd.DatetimeIndex(df.index).day_of_year.values.astype(float)
    B      = 2 * np.pi * (doy - 1) / 365
    Ra_est = GHI_daily * 3600 / 1e6 / 0.75   # MJ/m²/day

    T_mean_daily = pd.Series(T2m).groupby(
        pd.DatetimeIndex(df.index).date).transform("mean").values
    T_max_daily  = pd.Series(T2m).groupby(
        pd.DatetimeIndex(df.index).date).transform("max").values
    T_min_daily  = pd.Series(T2m).groupby(
        pd.DatetimeIndex(df.index).date).transform("min").values
    T_range      = np.clip(T_max_daily - T_min_daily, 0, None)

    ET0_daily_mm = np.clip(
        0.0023 * Ra_est * (T_mean_daily + 17.8) * T_range**0.5, 0, None)

    # Distribute daily ET0 to hourly proportional to GHI (daytime hours only)
    ET0_hourly = np.where(
        GHI > 1,
        ET0_daily_mm * GHI / np.where(GHI_daily < 1, 1, GHI_daily),
        0.0
    )

    # Water savings (Eq. 14)
    F_shad    = df["F_shad"].values
    W_saved_h = P["alpha_shade"] * F_shad * ET0_hourly   # mm/hour

    W_saved_season  = float(np.sum(W_saved_h[season]))
    ET0_season_mm   = float(np.sum(ET0_hourly[season]))
    ET0_annual_mm   = float(np.sum(ET0_hourly))

    # LER_water — CORRECTED: season denominator
    LER_water_season = (W_saved_season / ET0_season_mm * 100
                        if ET0_season_mm > 0 else 0.0)
    # Keep annual version for reference (old definition — do NOT use in paper)
    LER_water_annual = (W_saved_season / ET0_annual_mm * 100
                        if ET0_annual_mm > 0 else 0.0)

    return {
        "W_saved_mm_season":     round(W_saved_season,  2),
        "ET0_season_mm":         round(ET0_season_mm,   1),
        "ET0_annual_mm":         round(ET0_annual_mm,   1),
        "LER_water_season_pct":  round(LER_water_season, 2),
        "LER_water_annual_pct":  round(LER_water_annual, 2),
    }


def compute_AD(df: pd.DataFrame,
               site: str,
               V_dig_m3: float,
               HRT_days: float,
               LER_crop: float,
               scenario: str = "S0") -> dict:
    """
    Compute annual biogas production and digester heat balance.

    Steps:
    1. Compute effective digester temperature T_dig_eff (Eq. 16)
       T_dig_eff = clip(T_amb_monthly_mean + 5,  26,  37)  °C
    2. Temperature-corrected BMP (Eq. 17 — Arrhenius)
       BMP_T = BMP_ref * exp(theta * (T_dig_eff - T_ref))
    3. Feedstock volatile solids (VS) from crop residues
       VS_input = fruit_yield * LER_crop * R_res * DM * VS_fraction  (kg/ha/yr)
    4. OLR check: OLR = VS_input / (365 * V_dig)  (kg VS/m³/day)
    5. Annual biogas energy (Eq. 18 simplified)
       E_biogas = VS_input * BMP_T_avg * CH4_fraction * LHV_CH4
    6. Digester heat demand (Eq. 18)
       Q_heat = Q_loss_cond + Q_inflow - Q_reaction

    Parameters
    ----------
    df       : hourly DataFrame with T2m
    site     : site name (for SITES config)
    V_dig_m3 : digester volume (m³)
    HRT_days : hydraulic retention time (days)
    LER_crop : crop yield ratio (used to scale residue input)
    scenario : S0–S6 (affects BMP multiplier and capture efficiency)

    Returns
    -------
    dict with all AD outputs
    """
    from config_00 import SCENARIOS
    P   = PARAMS
    cfg = SITES[site]
    sc  = SCENARIOS[scenario]

    # ── 1. Monthly mean ambient temperature ──────────────────────────────────
    idx       = pd.DatetimeIndex(df.index)
    T_monthly = df.groupby(idx.month)["T2m"].mean()

    # ── 2. Effective digester temperature (Eq. 16) ───────────────────────────
    T_dig_eff_monthly = T_monthly.apply(
        lambda T: float(np.clip(T + P["T_amb_boost_degC"],
                                P["T_dig_min_degC"],
                                P["T_ref_degC"]))
    )

    # ── 3. Arrhenius BMP correction (Eq. 17) ─────────────────────────────────
    BMP_T_monthly = P["BMP_ref"] * np.exp(
        P["theta_arrhenius"] * (T_dig_eff_monthly - P["T_ref_degC"])
    )
    BMP_T_monthly *= sc["BMP_mult"]    # scenario multiplier (S1 co-digestion)
    BMP_T_avg      = float(BMP_T_monthly.mean())

    # ── 4. Feedstock VS input (kg VS/ha/yr) ──────────────────────────────────
    # VS from tomato residues (DM=6% — Mohammedi 2023)
    VS_residues = (cfg["fruit_yield_t_ha"] * 1000
                   * LER_crop
                   * cfg["R_res"]
                   * cfg["DM"]
                   * cfg["VS_fraction"])
    # VS from cattle manure co-substrate
    VS_manure = (cfg["manure_input_t_ha"] * 1000
                 * cfg["manure_DM"]
                 * cfg["manure_VS_fraction"])
    VS_input = VS_residues + VS_manure   # total kg VS/ha/yr

    # ── 5. OLR check ─────────────────────────────────────────────────────────
    OLR = VS_input / (365 * V_dig_m3)    # kg VS/m³/day

    # ── 6. Annual biogas energy ───────────────────────────────────────────────
    # Methane volume (Nm³/ha/yr)
    CH4_vol_m3 = (VS_input
                  * BMP_T_avg / 1e6         # NmL/gVS → Nm³/kg
                  * 1000                    # gVS → kgVS
                  * sc["eta_cap"])          # capture efficiency

    # Energy content (kWh/ha/yr)
    E_biogas_kWh = CH4_vol_m3 * P["LHV_CH4_MJ_m3"] / 3.6   # MJ → kWh

    # ── 7. Digester heat balance (Eq. 18) ────────────────────────────────────
    # Wall surface area (cylindrical digester: H = D assumption)
    D_m   = (4 * V_dig_m3 / np.pi) ** (1/3)
    A_wall = np.pi * D_m * D_m + 2 * np.pi * (D_m/2)**2   # lateral + top + bottom

    T_amb_annual = float(df["T2m"].mean())
    T_dig_annual = float(T_dig_eff_monthly.mean())

    Q_loss_kWh   = (P["U_eff_W_m2K"] * A_wall
                    * (T_dig_annual - T_amb_annual)
                    * 8760 / 1000)   # W → kWh/yr

    # Substrate heating demand
    flow_rate_m3_day = V_dig_m3 / HRT_days
    Q_inflow_kWh     = (flow_rate_m3_day * 365
                        * P["rho_substrate"]
                        * P["Cp_substrate"]
                        * max(0, T_dig_annual - P["T_inlet_degC"])
                        / 3600)       # kJ → kWh

    Q_reaction_kWh   = P["Q_reaction_frac"] * E_biogas_kWh
    Q_heat_total_kWh = max(0, Q_loss_kWh + Q_inflow_kWh - Q_reaction_kWh)

    return {
        "BMP_avg_NmL_gVS":      round(BMP_T_avg,    1),
        "VS_input_kg_ha":       round(VS_input,      0),
        "OLR_kgVS_m3d":         round(OLR,           3),
        "CH4_vol_m3_ha":        round(CH4_vol_m3,    1),
        "E_biogas_kWh_ha":      round(E_biogas_kWh,  1),
        "Q_heat_kWh_ha":        round(Q_heat_total_kWh, 1),
        "Q_loss_kWh":           round(Q_loss_kWh,    1),
        "Q_inflow_kWh":         round(Q_inflow_kWh,  1),
        "T_dig_avg_degC":       round(T_dig_annual,  1),
        "T_dig_monthly":        T_dig_eff_monthly.to_dict(),
        "BMP_monthly":          BMP_T_monthly.to_dict(),
    }


def modules_per_ha(beta_deg: float, d_row_m: float) -> int:
    """
    Compute number of modules fitting on 1 ha given tilt and row spacing.
    Rows run East-West (perpendicular to South-facing panels).
    n_rows  = field_depth / d_row
    n_cols  = row_length / module_length
    """
    field_depth = LAND_AREA_M2 / ROW_LENGTH_M   # 100 m
    n_rows = int(field_depth / d_row_m)
    n_cols = int(ROW_LENGTH_M / MODULE_LENGTH_M)
    return max(1, n_rows * n_cols)


def reference_pv_kWh(df: pd.DataFrame, beta_deg: float) -> float:
    """
    Compute annual PV yield for a dense-pack open-field reference array.
    Used as denominator for LER_PV (Definition A).
    Dense-pack: d_row = MODULE_LENGTH * cos(beta) → no inter-row shading
    (GCR = 1.0, but modules do not shade each other because rows are
    spaced at exactly the module projected width).
    """
    d_ref  = MODULE_LENGTH_M * np.cos(np.radians(beta_deg))
    n_ref  = modules_per_ha(beta_deg, max(d_ref, 0.5))

    # No shading in reference
    df_ref = df.copy()
    df_ref["F_shad"] = 0.0
    df_ref = compute_POA(df_ref, beta_deg)
    df_ref = compute_PV(df_ref, n_ref, f_PV_heat=0.0)
    return float(df_ref["E_PV_kWh"].sum())


def eLER_objective(x: np.ndarray,
                   df: pd.DataFrame,
                   site: str,
                   scenario: str = "S0",
                   PAR_sat: float = 174.0,
                   return_full: bool = False):
    """
    Main objective function for Differential Evolution.

    Parameters
    ----------
    x      : design vector [beta, d_row, H_m, V_dig, HRT, f_PV_heat]
    df     : hourly climate DataFrame for the site
    site   : site name
    scenario : AD scenario (S0–S6)
    PAR_sat  : crop light saturation (W/m²)
    return_full : if True, return full results dict instead of scalar

    Returns
    -------
    float : eLER (Definition A) — maximized by DE
            returns DE_SETTINGS["infeasibility_penalty"] if constraints violated
    """
    beta_deg, d_row_m, H_m_m, V_dig_m3, HRT_days, f_PV_heat = x

    # ── Feasibility check ─────────────────────────────────────────────────────
    PENALTY = DE_SETTINGS["infeasibility_penalty"]

    # ── Step 1: Solar geometry + shading ────────────────────────────────────
    df_s = compute_solar_angles(df, SITES[site]["lat"])
    df_s = compute_shading(df_s, beta_deg, d_row_m, H_m_m)
    df_s = compute_POA(df_s, beta_deg)

    # ── Step 2: PV model ─────────────────────────────────────────────────────
    n_mod = modules_per_ha(beta_deg, d_row_m)
    df_s  = compute_PV(df_s, n_mod, f_PV_heat)

    E_PV_total_kWh = float(df_s["E_PV_kWh"].sum())
    E_PV_sold_kWh  = float(df_s["E_PV_sold_kWh"].sum())

    # ── Step 3: Crop yield ────────────────────────────────────────────────────
    crop_res = compute_crop_yield(df_s, PAR_sat)
    LER_crop = crop_res["LER_crop"]

    # ── Step 4: ET reduction ─────────────────────────────────────────────────
    water_res = compute_ET_reduction(df_s, site)

    # ── Step 5: AD model ─────────────────────────────────────────────────────
    ad_res = compute_AD(df_s, site, V_dig_m3, HRT_days, LER_crop, scenario)

    # OLR feasibility constraint
    OLR = ad_res["OLR_kgVS_m3d"]
    if not (DE_SETTINGS["OLR_min"] <= OLR <= DE_SETTINGS["OLR_max"]):
        if return_full:
            return None
        return PENALTY

    E_biogas_kWh   = ad_res["E_biogas_kWh_ha"]
    Q_heat_kWh     = ad_res["Q_heat_kWh_ha"]

    # ESR (Energy Self-sufficiency Ratio)
    ESR = (E_PV_total_kWh + E_biogas_kWh) / max(Q_heat_kWh, 1)

    # ── Step 6: eLER (Definition A) ──────────────────────────────────────────
    # LER_PV (Def A): APV PV yield / reference open-field dense-pack yield
    E_PV_ref_kWh = reference_pv_kWh(df_s, beta_deg)
    LER_PV_A     = E_PV_sold_kWh / max(E_PV_ref_kWh, 1)

    # LER_PV (Def B): GCR — for reporting only
    GCR      = float(df_s["GCR"].iloc[0])
    LER_PV_B = GCR

    # LER_biogas: APV biogas / reference standalone AD
    # Reference AD: same V_dig, same HRT, but residue from open-field yield
    # (LER_crop = 1.0 in reference)
    ad_ref   = compute_AD(df_s, site, V_dig_m3, HRT_days,
                          LER_crop=1.0, scenario=scenario)
    E_bio_ref = ad_ref["E_biogas_kWh_ha"]
    LER_biogas = E_biogas_kWh / max(E_bio_ref, 1)

    eLER = LER_crop + LER_PV_A + LER_biogas

    if not return_full:
        return float(eLER)

    # ── Full results dict (used after optimization) ───────────────────────────
    return {
        # Design variables
        "beta_deg":       beta_deg,
        "d_row_m":        d_row_m,
        "H_m_m":          H_m_m,
        "V_dig_m3":       V_dig_m3,
        "HRT_days":       HRT_days,
        "f_PV_heat":      f_PV_heat,
        "GCR_pct":        round(GCR * 100, 2),
        "OLR_kgVS_m3d":   round(OLR, 3),
        "n_modules":      n_mod,
        # E1 — Energy
        "PV_total_MWh_ha":    round(E_PV_total_kWh / 1000, 2),
        "PV_sold_MWh_ha":     round(E_PV_sold_kWh  / 1000, 2),
        "biogas_total_MWh_ha":round(E_biogas_kWh   / 1000, 2),
        "heat_demand_MWh_ha": round(Q_heat_kWh     / 1000, 2),
        "ESR":                round(ESR, 1),
        "BMP_avg_NmL_gVS":    ad_res["BMP_avg_NmL_gVS"],
        # eLER
        "LER_crop":    round(LER_crop,   3),
        "LER_PV_defA": round(LER_PV_A,  3),
        "LER_PV_defB": round(LER_PV_B,  3),
        "LER_biogas":  round(LER_biogas, 3),
        "eLER_defA":   round(eLER,       3),
        "LER_2C":      round(LER_crop + LER_PV_A, 3),
        # Water (corrected)
        **water_res,
        # AD internals
        **{k: v for k, v in ad_res.items()
           if k not in ("T_dig_monthly", "BMP_monthly")},
    }
