function S = apvad_sites(name)
%APVAD_SITES Site parameters for the four APV-AD study sites.
%
%   S = APVAD_SITES()      returns a struct with one field per site.
%   S = APVAD_SITES(NAME)  returns the parameter struct for one site.
%
%   Ported verbatim from notebooks/config_00.py (SITES) so that the dynamic
%   MATLAB model and the static Python model share a single set of site
%   parameters. If config_00.py changes, mirror the change here.
%
%   Sites: Konya (BSk), Almeria (BSh), Ouagadougou (BSh), Freiburg (Cfb).
%
%   See also APVAD_PARAMS, APVAD_DYN_PARAMS.

% ---------------------------------------------------------------------
% Konya, Turkey -- BSk, cold semi-arid
% ---------------------------------------------------------------------
S.Konya = struct( ...
    'name',                 'Konya', ...
    'lat',                  37.87, ...          % deg N
    'lon',                  32.49, ...          % deg E
    'elevation_m',          1016, ...
    'min_beta_deg',         20.0, ...
    'koppen',               'BSk', ...
    'timezone_utc',         3, ...
    'planting_date',        '04-25', ...
    'harvest_date',         '10-30', ...
    'season_days',          189, ...
    'fruit_yield_t_ha',     60.0, ...           % fresh fruit, t/ha
    'R_res',                0.80, ...           % residue-to-fruit ratio
    'DM',                   0.06, ...           % dry-matter fraction of residues
    'VS_fraction',          0.85, ...           % VS/DM of residues
    'PAR_sat',              174.0, ...          % W/m2, tomato light saturation
    'manure_input_t_ha',    10.0, ...
    'manure_DM',            0.20, ...
    'manure_VS_fraction',   0.80, ...
    'p_tomato_usd_t',       300.0, ...
    'p_elec_usd_kWh',       0.06, ...
    'p_biogas_usd_kWh',     0.08, ...
    'discount_rate',        0.08, ...
    'grid_ef_tCO2_MWh',     0.438, ...
    'carbon_price_usd_tCO2', 15.0);

% ---------------------------------------------------------------------
% Almeria, Spain -- BSh, hot semi-arid
% ---------------------------------------------------------------------
S.Almeria = struct( ...
    'name',                 'Almeria', ...
    'lat',                  36.83, ...
    'lon',                  -2.46, ...
    'elevation_m',          20, ...
    'min_beta_deg',         20.0, ...
    'koppen',               'BSh', ...
    'timezone_utc',         1, ...
    'planting_date',        '03-01', ...
    'harvest_date',         '06-30', ...
    'season_days',          122, ...
    'fruit_yield_t_ha',     60.0, ...
    'R_res',                0.80, ...
    'DM',                   0.06, ...
    'VS_fraction',          0.85, ...
    'PAR_sat',              174.0, ...
    'manure_input_t_ha',    10.0, ...
    'manure_DM',            0.20, ...
    'manure_VS_fraction',   0.80, ...
    'p_tomato_usd_t',       400.0, ...
    'p_elec_usd_kWh',       0.09, ...
    'p_biogas_usd_kWh',     0.09, ...
    'discount_rate',        0.06, ...
    'grid_ef_tCO2_MWh',     0.167, ...
    'carbon_price_usd_tCO2', 65.0);

% ---------------------------------------------------------------------
% Ouagadougou, Burkina Faso -- BSh, tropical semi-arid
% ---------------------------------------------------------------------
S.Ouagadougou = struct( ...
    'name',                 'Ouagadougou', ...
    'lat',                  12.37, ...
    'lon',                  -1.53, ...
    'elevation_m',          303, ...
    'min_beta_deg',         12.0, ...
    'koppen',               'BSh', ...
    'timezone_utc',         0, ...
    'planting_date',        '07-01', ...
    'harvest_date',         '10-30', ...
    'season_days',          122, ...
    'fruit_yield_t_ha',     60.0, ...
    'R_res',                0.80, ...
    'DM',                   0.06, ...
    'VS_fraction',          0.85, ...
    'PAR_sat',              174.0, ...
    'manure_input_t_ha',    10.0, ...
    'manure_DM',            0.20, ...
    'manure_VS_fraction',   0.80, ...
    'p_tomato_usd_t',       250.0, ...
    'p_elec_usd_kWh',       0.12, ...
    'p_biogas_usd_kWh',     0.08, ...
    'discount_rate',        0.10, ...
    'grid_ef_tCO2_MWh',     0.632, ...
    'carbon_price_usd_tCO2', 12.0);

% ---------------------------------------------------------------------
% Freiburg im Breisgau, Germany -- Cfb, oceanic temperate
% ---------------------------------------------------------------------
S.Freiburg = struct( ...
    'name',                 'Freiburg', ...
    'lat',                  47.99, ...
    'lon',                  7.85, ...
    'elevation_m',          278, ...
    'min_beta_deg',         22.0, ...
    'koppen',               'Cfb', ...
    'timezone_utc',         1, ...
    'planting_date',        '05-01', ...
    'harvest_date',         '10-15', ...
    'season_days',          167, ...
    'fruit_yield_t_ha',     30.0, ...           % DLG 2023 German open-field
    'R_res',                0.80, ...
    'DM',                   0.06, ...
    'VS_fraction',          0.85, ...
    'PAR_sat',              174.0, ...
    'manure_input_t_ha',    10.0, ...
    'manure_DM',            0.20, ...
    'manure_VS_fraction',   0.80, ...
    'p_tomato_usd_t',       350.0, ...
    'p_elec_usd_kWh',       0.09, ...
    'p_biogas_usd_kWh',     0.09, ...
    'discount_rate',        0.05, ...
    'grid_ef_tCO2_MWh',     0.380, ...
    'carbon_price_usd_tCO2', 65.0);

if nargin > 0
    if ~isfield(S, name)
        error('apvad_sites:unknownSite', ...
              'Unknown site "%s". Available: %s.', ...
              name, strjoin(fieldnames(S)', ', '));
    end
    S = S.(name);
end
end
